version: '2'

services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  app:
    depends_on:
      - db
    build: .
    environment:
        - RAILS_ENV=development
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

volumes:
  postgres:
